os: linux
language: cpp
compiler: clang
addons: 
  apt: 
    sources: 
      - sourceline: 'ppa:snaipewastaken/ppa'
    packages:
      - criterion-dev
      - clang
      - libboost-all-dev
    update: true
install:
  - git submodule update --init
  - make build
  - make
script:
  - ./build/test
