os: linux
dist: bionic
language: cpp
compiler: clang
addons: 
  apt: 
    sources: 
      - universe
      - sourceline: 'ppa:snaipewastaken/ppa'
    packages:
      - cmake
      - criterion-dev
      - clang
      - libboost1.65-tools-dev
    update: true
install:
  - git submodule update --init
  - mkdir build
  - cd build && cmake .. && make
script:
  - ./build/test
