os: osx
language: cpp
compiler: clang
addons: 
  homebrew: 
    packages:
      - cmake
      - snaipe/soft/criterion
      - boost
    update: true
install:
  - git submodule update --init
  - mkdir build
  - make all
script:
  - ./build/test
