os: linux
dist: bionic
language: cpp
compiler: clang
addons: 
  apt: 
    sources: 
      - sourceline: 'ppa:snaipewastaken/ppa'
      - sourceline: 'ppa:mhier/libboost-latest'
    packages:
      - cmake
      - criterion-dev
      - clang
      - libboost
    update: true
install:
  - git submodule update --init
  - mkdir build
  - cd build && cmake .. && make
script:
  - ./build/test
