language: cpp
compiler: clang
addons: 
  apt: 
    packages: libboost-all-dev
install:
  - sudo add-apt-repository ppa:snaipewastaken/ppa
  - sudo apt-get update
  - sudo apt-get install criterion-dev
  - sudo apt-get install clang
  - make build
  - make
script:
  - ./build/test
