#!/usr/bin/env python3

import argparse

from assembler import Assembler

if __name__ == '__main__':
  parser = argparse.ArgumentParser(description='Intel8080 assembler')
  parser.add_argument('file')
  parser.add_argument('-o', '--output')
  parser.add_argument('-v', '--verbose', action='store_true')
  args = parser.parse_args()

  with open(args.file, 'r') as f:
    asm = Assembler(f.read())
    f.close()

  asm.assemble()

  if args.verbose:
    asm.dump_sections()

  if args.output is None:
    args.output = ''.join(args.file.split('.')[:-1]) + '.bin'

  with open(args.output, 'wb') as f:
    f.write(bytes(asm.output))
